version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - OLLAMA_URL=http://ollama:11434

  ollama:
    build: 
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - '11434:11434'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '8501:8501'
    depends_on:
      - api
      - ollama
    environment:
      - API_URL=http://api:8080
